version: '3'
services:
    docker-registry:
        image: registry:2
        container_name: registry
        volumes:
        - "/home/centos/data/registry:/var/lib/registry"
        ports:
        - "5000:5000"
        restart: always

    docker-registry-ui:
        image: parabuzzle/craneoperator:latest
        container_name: registry-ui
        ports:
        - "18088:80"
        environment:
        - REGISTRY_HOST=docker-registry
        - REGISTRY_PORT=5000
        - REGISTRY_PROTOCOL=http
        - SSL_VERIFY=false
        - USERNAME=admin
        - PASSWORD=mypassword
        restart: always
        depends_on:
        - docker-registry
