version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - 8087:8080
      - 50000:50000
    volumes:
      - /home/centos/data/univad-task/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - priv-net

networks:
  priv-net:
    external: true
